### ISSUE TITLE
License File

### ISSUE THREAD

**Issue by myles** [pedrovanzella/Flask-DODDNS#1]
I made a bunch of changes to your project (moved from DO to Linode, I'm using libcloud instead of the requests library, and to be hosted on Heroku) and would like to share them on GitHub. Not having a license file in your code means I can't push any of my changes to GitHub. If this is deliberate then I'm sorry for bugging you.

**Comment by pedrovanzella** [comment]
It's MIT Licensed, just pushed a license file.
